import React from "react";
import AuthLayout from "@/components/modules/authLayout";
import Head from "next/head";
import SingUpSection from "@/components/rendering/auth/singUpSection";
import { parseCookies } from "nookies";

export default function SignupPage() {
  return (
    <>
      <Head>
        <title>WaoSim | Signup</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconIcon.svg" />
      </Head>
      <main>
        <AuthLayout>
          <SingUpSection />
        </AuthLayout>{" "}
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const { req } = context;

  const cookies = parseCookies({ req });

  if (cookies?.waotoken) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }

  return {
    props: {
      token: cookies?.waotoken || "",
    },
  };
}
