import Head from "next/head";
import dynamic from "next/dynamic";
// import Sidebar from "../components/rendering/Sidebar"
import Script from "next/script";
import DashboardPage from "@/components/rendering/dashboardPage";

const Sidebar = dynamic(() => import("@/components/rendering/Sidebar"));

export default function HomePage() {
  
  return (
    <>
      <Head>
        <title>WaoSim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <meta property="og:image" content="/path/to/your/thumbnail.jpg" /> */}
        <link rel="icon" href="/faviconIcon.svg" />
      </Head>

      {/* <Script
        src="https://d3jdpgtmfh7sez.cloudfront.net/v1/assets/static/injector.js"
        strategy="afterInteractive"
        data-account="HFBBNed8efTWhrh"
        onLoad={() => console.log("Script has loaded")}
        type="module"
      /> */}

      <main>
        <DashboardPage/>
      </main>
    </>
  );
}

// export async function getServerSideProps({ req }: any) {
//   const { isError, response } = await getAllCountryRegion();

//   return {
//     props: {
//       response: response?.data,
//     },
//   };
// }
