import AuthLayout from "@/components/modules/authLayout";
import Head from "next/head";
import UpdatePasswordSection from "@/components/rendering/auth/updatePasswordSection";
import { parseCookies } from "nookies";

export default function UpdatePasswordPage() {
  return (
    <>
      <Head>
        <title>WaoSim | Update Password</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconIcon.svg" />
      </Head>
      <main>
        <AuthLayout>
          <UpdatePasswordSection />
        </AuthLayout>{" "}
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const { req } = context;
  const { email_mobile } = context.query;

  const cookies = parseCookies({ req });

  if (cookies?.waotoken) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  } else if (!email_mobile) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      token: cookies?.waotoken || "",
    },
  };
}
